# Generated by Django 4.2.1 on 2023-05-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='total',
            new_name='summatory',
        ),
    ]
