# Generated by Django 4.2.1 on 2023-05-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_total_productsmodel_summatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproducts',
            name='bill',
            field=models.CharField(max_length=10, verbose_name='No. factura compra'),
        ),
        migrations.AlterField(
            model_name='incomingproducts',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productsmodel', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='incomingproducts',
            name='dateIncoming',
            field=models.DateTimeField(verbose_name='Fecha ingreso'),
        ),
        migrations.AlterField(
            model_name='incomingproducts',
            name='quantityIncoming',
            field=models.IntegerField(verbose_name='Cantidad ingresada'),
        ),
        migrations.AlterField(
            model_name='outcomingproducts',
            name='bill',
            field=models.CharField(max_length=10, verbose_name='No. factura venta'),
        ),
        migrations.AlterField(
            model_name='outcomingproducts',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productsmodel', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='outcomingproducts',
            name='dateOutcoming',
            field=models.DateTimeField(verbose_name='Fecha salida'),
        ),
        migrations.AlterField(
            model_name='outcomingproducts',
            name='quantityOutcoming',
            field=models.IntegerField(verbose_name='Cantidad salida'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.CharField(choices=[('0', 'Árboles y arbustos'), ('1', 'Césped y tapizantes'), ('2', 'Anuales'), ('3', 'Florales'), ('4', 'Palmeras'), ('5', 'Helechos'), ('6', 'Trepadoras'), ('7', 'Acuáticas')], max_length=1, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='incomings',
            field=models.IntegerField(verbose_name='Entradas'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='initial_stock',
            field=models.IntegerField(verbose_name='Stock inicial'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='outcomings',
            field=models.IntegerField(verbose_name='Salidas'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='product',
            field=models.CharField(max_length=100, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='summatory',
            field=models.IntegerField(verbose_name='Existencias'),
        ),
    ]
