# Generated by Django 4.2.1 on 2023-05-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_productsmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingproducts',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='outcomingproducts',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio público'),
        ),
    ]
