# Generated by Django 4.2.1 on 2023-05-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_incomingproducts_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproducts',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
