# Generated by Django 4.2.1 on 2023-05-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_incomingproducts_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingproducts',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='incomingproducts',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='incomingproducts',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre o razón social'),
        ),
        migrations.AddField(
            model_name='incomingproducts',
            name='supplier',
            field=models.CharField(default='', max_length=100, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='incomingproducts',
            name='telephone',
            field=models.CharField(default='', max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='incomingproducts',
            name='bill',
            field=models.CharField(default='', max_length=10, verbose_name='No. factura compra'),
        ),
    ]
